@startuml
actor Cliente
actor Administrador
actor Empleado

Cliente --> (Consultar Disponibilidad)
Cliente --> (Realizar Reserva)
Cliente --> (Modificar/Cancelar Reserva)
Cliente --> (Recibir Confirmación)

(Realizar Reserva) ..> (Realizar Pago) : <<include>>

Administrador --> (Gestionar Habitaciones)
Administrador --> (Generar Reportes)
Administrador --> (Administrar Usuarios)

Empleado --> (Consultar Reservas del Día)
@enduml
